# Generated by Django 5.1.3 on 2024-11-30 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='crated_date',
            new_name='created_date',
        ),
    ]
