# Generated by Django 5.0.6 on 2024-08-20 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
