# Generated by Django 5.0.6 on 2024-08-28 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_account_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
